{
  "title": "Getting funcap plugin work in IDA pro",
  "link": "https://reverseengineering.stackexchange.com/questions/5974/getting-funcap-plugin-work-in-ida-pro",
  "content": "I am trying to use funcap plugin in IDA pro 6.1. However, after loading the plugin (with Alt+F7) and pressing the debugger's run button, it returns me:\n\n```\nInternal error 30191 \n\n```\nAny idea what is the problem?\n\nP.S.: I have tried with both Python 2.6 and 2.7.\n\n",
  "votes": "3",
  "answers": 1,
  "views": "906",
  "tags": [
    "ida",
    "ida-plugin"
  ],
  "user": "user3403765",
  "time": "Jul 29, 2014 at 17:10",
  "comments": [],
  "answers_data": [
    {
      "content": "By any chance do you have the IDAStealth plugin installed? If so, do you have SEH debugging support features enabled? \n\nAs per the bugfix for the plugin:\n\n```\nBugfix: If any of the SEH debugging support features was used an \"internal error 30191\" would be raised in IDA as soon as the exception occurred in the debuggee\n\n```\nhttp://newgre.net/idastealth\n\n",
      "votes": "4",
      "user": "Fred Concklin",
      "time": "Jul 30, 2014 at 3:02",
      "is_accepted": false,
      "comments": [
        {
          "user": "user3403765",
          "text": "Thanks for your reply. But, no. I don't.",
          "time": null
        }
      ]
    }
  ]
}