{
    "title": "Extract PYZ Error",
    "link": "https://reverseengineering.stackexchange.com/questions/26072/extract-pyz-error",
    "content": "<html><body><div class=\"s-prose js-post-body\" itemprop=\"text\">\n <p>\n  I successfully recovered some PYC files from an ELF built by PyInstaller (\n  <a href=\"https://github.com/extremecoders-re/pyinstxtractor/wiki/Extracting-Linux-ELF-binaries\" rel=\"nofollow noreferrer\">\n   https://github.com/extremecoders-re/pyinstxtractor/wiki/Extracting-Linux-ELF-binaries\n  </a>\n  ). There is a PYZ archive in the dump. I tried to use pyi-archive_viewer to open and/or extract some modules from the PYZ. I receive an AttributeError \"ZlibArchive object has no attribute open openEmbedded.\"\n </p>\n <p>\n  The error occurs on line 134 of the source (\n  <a href=\"https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/utils/cliutils/archive_viewer.py\" rel=\"nofollow noreferrer\">\n   https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/utils/cliutils/archive_viewer.py\n  </a>\n  )\n </p>\n <p>\n  I believe something is incorrectly parsed/output during extraction...? Has anyone else seen this?\n </p>\n</div>\n</body></html>",
    "votes": "1",
    "answers": 1,
    "views": "2k",
    "tags": [
        "decompilation",
        "elf",
        "python"
    ],
    "user": "armor",
    "time": "Oct 6, 2020 at 19:36",
    "comments": [],
    "answers_data": [
        {
            "content": "<html><body><div class=\"s-prose js-post-body\" itemprop=\"text\">\n <p>\n  For anyone else this happens to... Ensure you use the same Python version as the original author.\n </p>\n <p>\n  That is, I originally created the ELF with Python 3.7. But I tried the reversing process on a different machine - with Python 3.8. Learn from my mistake!\n </p>\n</div>\n</body></html>",
            "votes": "0",
            "user": "armor",
            "time": "Oct 6, 2020 at 20:23",
            "is_accepted": false,
            "comments": [
                {
                    "user": "Abdullah Mohamed",
                    "text": "<span class=\"comment-copy\">I'm curious on how did you discover that it was a mismatching Python version issue? Was it coincidence? Or you've done some kind of static analysis to the source code of the python files and figured it out?</span>",
                    "time": null
                },
                {
                    "user": "armor",
                    "text": "<span class=\"comment-copy\">a dash of trial and error, and a dash of reading the python release notes. though I cannot recall what tipped me off in the latter :/</span>",
                    "time": null
                },
                {
                    "user": "Abdullah Mohamed",
                    "text": "<span class=\"comment-copy\">That was definitely a nice and thorough learning experience, thanks for sharing the answer!</span>",
                    "time": null
                }
            ]
        }
    ]
}