{
    "title": "IDA Unknown Exception Code 6F4",
    "link": "https://reverseengineering.stackexchange.com/questions/27041/ida-unknown-exception-code-6f4",
    "content": "<html><body><div class=\"s-prose js-post-body\" itemprop=\"text\">\n <p>\n  So basically I had set a breakpoint on a WINAPI function call. When I tried to run the program and step over the breakpoint, the program exits with the popup window:\n  <code>\n   unknown exception code 6F4 (exc.code 6f4, tid 704)\n  </code>\n  . The function does not return any value as the program exits before that happens, so I can't tell if the function has returned a successful error code or not. What is this exception code, and why did this happen?\n </p>\n</div>\n</body></html>",
    "votes": "1",
    "answers": 1,
    "views": "786",
    "tags": [
        "ida",
        "debugging",
        "exception"
    ],
    "user": "kayanon",
    "time": "May 31, 2022 at 7:31",
    "comments": [
        {
            "user": "Tony",
            "text": "<html><body><span class=\"comment-copy\">\n Can you try to set the same breakpoint in x64dbg or in windbg and see if there is the same exception ? Try also to use an hardware breakpoint.\n</span>\n</body></html>",
            "time": null
        }
    ],
    "answers_data": [
        {
            "content": "<html><body><div class=\"s-prose js-post-body\" itemprop=\"text\">\n <pre><code>\\>cdb -c \"!error 6f4;q\" cdb | awk \"/Reading/,/quit/\"  \n0:000> cdb: Reading initial command '!error 6f4;q'   \n**Error code: (Win32) 0x6f4 (1780) - A null reference pointer was passed to the stub.**  \nquit: \n</code></pre>\n</div>\n</body></html>",
            "votes": "3",
            "user": "0xC0000022L",
            "time": "May 31, 2022 at 7:31",
            "is_accepted": false,
            "comments": []
        }
    ]
}