{
    "title": "When is EXCEPTION_REGISTRATION_RECORD created on the stack?",
    "link": "https://reverseengineering.stackexchange.com/questions/31559/when-is-exception-registration-record-created-on-the-stack",
    "content": "<html><body><div class=\"s-prose js-post-body\" itemprop=\"text\">\n <p>\n  I want to understand when\n  <code>\n   EXCEPTION_REGISTRATION_RECORD\n  </code>\n  s get created on the stack.\n </p>\n <ul>\n  <li>\n   Are they created when the program starts?\n  </li>\n  <li>\n   Are they created when we enter the function?\n  </li>\n  <li>\n   Or are they created only when the exception occurs?\n  </li>\n </ul>\n <p>\n  Is it true that there is one\n  <code>\n   EXCEPTION_REGISTRATION_RECORD\n  </code>\n  per\n  <code>\n   try\n  </code>\n  /\n  <code>\n   catch\n  </code>\n  ?\n </p>\n</div>\n</body></html>",
    "votes": "3",
    "answers": 1,
    "views": "99",
    "tags": [
        "seh"
    ],
    "user": "Bob5421",
    "time": "Feb 17, 2023 at 9:40",
    "comments": [
        {
            "user": "0xC0000022L",
            "text": "<html><body><span class=\"comment-copy\">\n Could you please clarify one thing. You tagged it as\n <a href=\"https://reverseengineering.stackexchange.com/questions/tagged/seh\">\n  seh\n </a>\n , but you mention\n <code>\n  try\n </code>\n /\n <code>\n  catch\n </code>\n . Now in MSVC C++ exceptions are implemented in terms of SEH, but are you solely interested in the C++ side of things or in general?\n</span>\n</body></html>",
            "time": null
        },
        {
            "user": "Bob5421",
            "text": "<html><body><span class=\"comment-copy\">\n I mean a MSVC C++ try/catch. I am interested in the wide general thing\n</span>\n</body></html>",
            "time": null
        },
        {
            "user": "peter ferrie",
            "text": "<html><body><span class=\"comment-copy\">\n I replaced my original answer because I was somehow describing the exception_record rather than the exception_registration_record.\n</span>\n</body></html>",
            "time": null
        }
    ],
    "answers_data": [
        {
            "content": "<html><body><div class=\"s-prose js-post-body\" itemprop=\"text\">\n <p>\n  EXCEPTION_REGISTRATION_RECORD is placed on the stack in anticipation of an exception occurring.  The \"try\" will put one there.  The record is part of a chain, for as many nested \"try\" statements as exist.  The nesting includes one function calling another function from within a try block.  Windows will also put a top-most handler there before the program starts, so there is always one on program start.\n </p>\n</div>\n</body></html>",
            "votes": "4",
            "user": "peter ferrie",
            "time": "Feb 25, 2023 at 23:24",
            "is_accepted": true,
            "comments": []
        }
    ]
}