{
    "title": "Getting funcap plugin work in IDA pro",
    "link": "https://reverseengineering.stackexchange.com/questions/5974/getting-funcap-plugin-work-in-ida-pro",
    "content": "I am trying to use funcap plugin in IDA pro 6.1. However, after loading the plugin (with Alt+F7) and pressing the debugger's run button, it returns me:\n<pre><code>Internal error 30191 \n</code></pre>\nAny idea what is the problem?\nP.S.: I have tried with both Python 2.6 and 2.7.\n",
    "votes": "3",
    "answers": 1,
    "views": "906",
    "tags": [
        "ida",
        "ida-plugin"
    ],
    "user": "user3403765",
    "time": "Jul 29, 2014 at 17:10",
    "comments": [],
    "answers_data": [
        {
            "content": "By any chance do you have the IDAStealth plugin installed? If so, do you have SEH debugging support features enabled? \nAs per the bugfix for the plugin:\n<pre><code>Bugfix: If any of the SEH debugging support features was used an \"internal error 30191\" would be raised in IDA as soon as the exception occurred in the debuggee\n</code></pre>\nhttp://newgre.net/idastealth\n",
            "votes": "4",
            "user": "Fred Concklin",
            "time": "Jul 30, 2014 at 3:02",
            "is_accepted": false,
            "comments": [
                {
                    "user": "user3403765",
                    "text": "<span class=\"comment-copy\">Thanks for your reply. But, no. I don't.</span>",
                    "time": null
                }
            ]
        }
    ]
}